# Generated by Django 3.2.9 on 2021-11-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acticles',
            new_name='Article',
        ),
    ]
